sudo: false
language: python
cache: pip
matrix:
  include:
    # Django 1.11
    - env: TOXENV=py34-dj111-wt2
      python: 3.4
    - env: TOXENV=py35-dj111-wt2
      python: 3.5
    - env: TOXENV=py36-dj111-wt2
      python: 3.6

    # Django 2
    - env: TOXENV=py35-dj2-wt2
      python: 3.5
    - env: TOXENV=py36-dj2-wt2
      python: 3.6
    - env: TOXENV=py37-dj2-wt2
      python: 3.7

    # Django 2.1
    - env: TOXENV=py35-dj21-wt2
      python: 3.5
    - env: TOXENV=py36-dj21-wt2
      python: 3.6
    - env: TOXENV=py37-dj21-wt2
      python: 3.6

    # Flake 8
    - env: TOXENV=flake8
      python: 3.6

  allow_failures:
    # wagtail dev
    - env: TOXENV=wagtaildev
      python: 3.6
install:
  - pip install codecov tox
script:
  - tox -e $TOXENV
services:
  - postgresql
after_success:
  - codecov
