sudo: false
language: python
cache: pip
matrix:
  include:
    # Wagtail 1.12
    - env: TOXENV=py27-dj18-postgres-wt112
      python: 2.7
    - env: TOXENV=py34-dj18-postgres-wt112
      python: 3.4
    - env: TOXENV=py35-dj18-postgres-wt112
      python: 3.5
    - env: TOXENV=py27-dj110-postgres-wt112
      python: 2.7
    - env: TOXENV=py34-dj110-postgres-wt112
      python: 3.4
    - env: TOXENV=py35-dj110-postgres-wt112
      python: 3.5
    - env: TOXENV=py27-dj111-postgres-wt112
      python: 2.7
    - env: TOXENV=py34-dj111-postgres-wt112
      python: 3.4
    - env: TOXENV=py35-dj111-postgres-wt112
      python: 3.5
    - env: TOXENV=py36-dj111-postgres-wt112
      python: 3.6

    # Flake 8
    - env: TOXENV=flake8
      python: 2.7
install:
  - pip install codecov tox
script:
  - tox -e $TOXENV
services:
  - postgresql
after_success:
  - codecov
